version: '3'
services:
  postgres:
    container_name: store-postgres-16
    image: postgres:16.2-alpine
    env_file:
      - .env
    ports:
      - 5434:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - store_net
    restart: unless-stopped

networks:
  store_net:
    driver: bridge

volumes:
  postgres:
